### ISSUE TITLE
请问Alpine如何使用该脚本重装？

### ISSUE THREAD

**Issue by xqdoo00o** [52fancy/NetInstallAlpine#3]
已经是Alpine系统了，想要重装下，使用该脚本提示
```
/dev/fd/64: line 73: can't create /etc/grub.d/40_custom: nonexistent directory
不支持当前系统
```
谢谢

**Comment by xqdoo00o** [comment]
使用该[文档](https://wiki.alpinelinux.org/wiki/Bootloaders) 从默认的Syslinux切换到Grub能重装了。
不过如果能支持Alpine默认的Syslinux就更好了

**Comment by 52fancy** [comment]
> 使用该[文档](https://wiki.alpinelinux.org/wiki/Bootloaders) 从默认的Syslinux切换到Grub能重装了。 不过如果能支持Alpine默认的Syslinux就更好了

我嫌syslinux麻烦，就没有搞了。。。。

**Comment by xqdoo00o** [comment]
好的
